name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: tamioEcoligo
          template: classic

          base: header, activity, community, repositories, metadata

          plugin_isometric: yes
          plugin_isometric_duration: full-year

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

          config_timezone: Asia/Ho_Chi_Minh
          filename: metrics.svg
